#pragma once
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#define IMGUI_DEFINE_MATH_OPERATORS
#include <iostream>
#include <Windows.h>
#include "memory/memory.h"
#include <dwmapi.h>
#include <tchar.h>
#include <TlHelp32.h>
#include <mmsystem.h>
#include <wrl/client.h>
#include <intrin.h>
#include <d3d11_1.h>
#include <dxgi1_4.h>
#include <d3dcompiler.h>
#include <DirectXMath.h>
#include <array>
#include <string>
#include <vector>
#include <unordered_map>
#include <algorithm>
#include <random>
#include <atomic>
#include <thread>
#include <shared_mutex>
#include <cctype>
#include <cstdint>
#include <iostream>
#include <memory>
#include <functional>
#include "ext/imgui.h"
#include "ext/imgui_internal.h"
#include "ext/imgui_impl_win32.h"
#include "ext/imgui_impl_dx11.h"
